source 'https://rubygems.org'

gem 'connection_pool'
gem 'jwt', '~> 3.1'
gem 'pg'
gem 'puma'
gem 'rack-test'
gem 'rackup'
gem 'rake', '~> 13.3'
gem 'rspec'
gem 'rspec-temp_dir', '~> 1.1'
gem 'rubocop', '~> 1.78'
gem 'rubocop-rake', '~> 0.7.1'
gem 'rubocop-rspec', '~> 3.6'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'tmpdir', '~> 0.3.1'
gem 'tty-command'
